# 端口号
server:
  port: 8763
# 服务注册相关配置
eureka:
  # 服务实例主机名
  instance:
    hostname: eureka8763.com
  # 服务提供者配置
  client:
    # 不进行注册（当服务注册中心是单点而非高可用时的配置方式）
    registerWithEureka: false
    # 不获取注册信息（当服务注册中心是单点而非高可用时的配置方式）
    fetchRegistry: false
    # 服务注册中心地址
    serviceUrl:
      #单机 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。
      defaultZone: http://eureka8762.com:8762/eureka/,http://eureka8761.com:8761/eureka/