server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test1
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver




#设置控制台日志级别 答应sql
logging:
  level:
    cn:
      cityworks: DEBUG



