server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/permissions
    username: postgres
    password: 123456
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
