server:
  port: 8080

spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/permissions
      username: postgres
      password: 123456
      driverClassName: org.postgresql.Driver

      # 使用druid数据源
#      type: com.alibaba.druid.pool.DruidDataSource
#      filters: stat
#      maxActive: 20
#      initialSize: 1
#      maxWait: 60000
#      minIdle: 1
#      timeBetweenEvictionRunsMillis: 60000
#      minEvictableIdleTimeMillis: 300000
#      validationQuery: select 'x'
#      testWhileIdle: true
#      testOnBorrow: false
#      testOnReturn: false
#      poolPreparedStatements: true
#      maxOpenPreparedStatements: 20

  jpa:
     hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        ddl-auto: update
     show-sql: true



