server:
  port: 8080

spring:
  application:
    name: customer-8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka8763.com:8763/eureka/,http://eureka8762.com:8762/eureka/,http://eureka8761.com:8761/eureka/



#开启熔断和降级
feign:
  hystrix:
    enabled: true